### ISSUE TITLE
name 'height' is not defined

### ISSUE THREAD

**Issue by schrockwell** [thejoelpatrol/macpaint_file#3]
```
❯ python converter.py --to-macpaint ~/Desktop/input.png ~/Desktop/output.mac
Traceback (most recent call last):
  File "/Users/rockwell/Projects/macpaint_file/converter.py", line 24, in <module>
    main(args)
  File "/Users/rockwell/Projects/macpaint_file/converter.py", line 11, in main
    macpaint_file = png.convert()
                    ^^^^^^^^^^^^^
  File "/Users/rockwell/Projects/macpaint_file/formats.py", line 131, in convert
    add_rows = MacPaintFile.HEIGHT - height
                                     ^^^^^^
NameError: name 'height' is not defined
```

If I change it to `self.height` I get a new error:

```
  File "/Users/rockwell/Projects/macpaint_file/macpaint.py", line 173, in _gen_packed_data
    assert len(bit_line) == cls.WIDTH / 8, f"error in condensing bytes into bits; line is only {len(bit_line)} bytes"
AssertionError: error in condensing bytes into bits; line is only 128 bytes
```

Here is the input PNG: 
![input](https://github.com/user-attachments/assets/aa156085-3553-45a1-b791-b7f21e48051f)

Any help would be appreciated, thank you.

**Comment by schrockwell** [comment]
Figured it out... there was a math error when calculating how much padding to add. Fixed in #4.

**Comment by thejoelpatrol** [comment]
Thanks, I commented on your PR. I think you have fixed the error here but probably added a different one, unless I'm mistaken.

**Comment by thejoelpatrol** [comment]
fixed by #4 
thanks!
